"""Создание таблицы hotels

Revision ID: 420a1e3f7bc4
Revises: 
Create Date: 2024-12-01 13:07:30.487194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '420a1e3f7bc4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_hotels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('price', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('saved_hotels')
    # ### end Alembic commands ###
